version: '3.1'
services:
  chainserver:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: STANDARD
    entrypoint: /bin/sh -c './server'
    ports:
      - "13900:13900"
    environment:
      RUNNING_IN_DOCKER: "true"
